"""Smoke tests for src/transmogrifier/detector.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_detector():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.detector")
    assert mod is not None
