"""Smoke tests for src/transmogrifier/profiles.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_profiles():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.profiles")
    assert mod is not None
