"""Smoke tests for src/transmogrifier/core.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_core():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.core")
    assert mod is not None
