"""Smoke tests for contracts/src_transmogrifier_rules/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_src_transmogrifier_rules_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_rules.interface")
    assert mod is not None

def test_rewrite_is_callable():
    """Function rewrite exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_rules.interface")
    fn = getattr(mod, "rewrite", None)
    assert fn is not None, "'rewrite' not found in contracts.src_transmogrifier_rules.interface"
    assert callable(fn)
