"""Smoke tests for src/transmogrifier/system_prompts.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_system_prompts():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.system_prompts")
    assert mod is not None

def test_get_system_prompt_is_callable():
    """Function get_system_prompt exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.system_prompts")
    fn = getattr(mod, "get_system_prompt", None)
    assert fn is not None, "'get_system_prompt' not found in transmogrifier.system_prompts"
    assert callable(fn)

def test_inject_system_prompt_is_callable():
    """Function inject_system_prompt exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.system_prompts")
    fn = getattr(mod, "inject_system_prompt", None)
    assert fn is not None, "'inject_system_prompt' not found in transmogrifier.system_prompts"
    assert callable(fn)
