"""Smoke tests for src/transmogrifier/validator.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_validator():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.validator")
    assert mod is not None
