"""Smoke tests for src/transmogrifier/backends/gemini.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_backends_gemini():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.backends.gemini")
    assert mod is not None
