"""Smoke tests for src/transmogrifier/kindex_integration.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_kindex_integration():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.kindex_integration")
    assert mod is not None

def test_is_available_is_callable():
    """Function is_available exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.kindex_integration")
    fn = getattr(mod, "is_available", None)
    assert fn is not None, "'is_available' not found in transmogrifier.kindex_integration"
    assert callable(fn)

def test_close_is_callable():
    """Function close exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.kindex_integration")
    fn = getattr(mod, "close", None)
    assert fn is not None, "'close' not found in transmogrifier.kindex_integration"
    assert callable(fn)
