"""Smoke tests for contracts/src_transmogrifier_system_prompts/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_src_transmogrifier_system_prompts_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_system_prompts.interface")
    assert mod is not None

def test_get_system_prompt_is_callable():
    """Function get_system_prompt exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_system_prompts.interface")
    fn = getattr(mod, "get_system_prompt", None)
    assert fn is not None, "'get_system_prompt' not found in contracts.src_transmogrifier_system_prompts.interface"
    assert callable(fn)

def test_inject_system_prompt_is_callable():
    """Function inject_system_prompt exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_system_prompts.interface")
    fn = getattr(mod, "inject_system_prompt", None)
    assert fn is not None, "'inject_system_prompt' not found in contracts.src_transmogrifier_system_prompts.interface"
    assert callable(fn)
