"""Smoke tests for contracts/src_transmogrifier_kindex_integration/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_src_transmogrifier_kindex_integration_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_kindex_integration.interface")
    assert mod is not None

def test_is_available_is_callable():
    """Function is_available exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_kindex_integration.interface")
    fn = getattr(mod, "is_available", None)
    assert fn is not None, "'is_available' not found in contracts.src_transmogrifier_kindex_integration.interface"
    assert callable(fn)

def test_close_is_callable():
    """Function close exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_kindex_integration.interface")
    fn = getattr(mod, "close", None)
    assert fn is not None, "'close' not found in contracts.src_transmogrifier_kindex_integration.interface"
    assert callable(fn)
