"""Smoke tests for src/transmogrifier/backends/openai.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_backends_openai():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.backends.openai")
    assert mod is not None
