"""Smoke tests for contracts/src_transmogrifier_task_classifier/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_src_transmogrifier_task_classifier_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_task_classifier.interface")
    assert mod is not None
