"""Smoke tests for src/transmogrifier/calibrate.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_calibrate():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.calibrate")
    assert mod is not None

def test_score_response_is_callable():
    """Function score_response exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.calibrate")
    fn = getattr(mod, "score_response", None)
    assert fn is not None, "'score_response' not found in transmogrifier.calibrate"
    assert callable(fn)
