"""Smoke tests for src/transmogrifier/mcp_server.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_mcp_server():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.mcp_server")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.mcp_server")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in transmogrifier.mcp_server"
    assert callable(fn)
