"""Smoke tests for src/transmogrifier/task_classifier.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_task_classifier():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.task_classifier")
    assert mod is not None
