"""Smoke tests for src/transmogrifier/rules.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_rules():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.rules")
    assert mod is not None
