"""Smoke tests for src/transmogrifier/cli.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_cli():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in transmogrifier.cli"
    assert callable(fn)

def test_detect_is_callable():
    """Function detect exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    fn = getattr(mod, "detect", None)
    assert fn is not None, "'detect' not found in transmogrifier.cli"
    assert callable(fn)

def test_classify_is_callable():
    """Function classify exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    fn = getattr(mod, "classify", None)
    assert fn is not None, "'classify' not found in transmogrifier.cli"
    assert callable(fn)

def test_translate_is_callable():
    """Function translate exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    fn = getattr(mod, "translate", None)
    assert fn is not None, "'translate' not found in transmogrifier.cli"
    assert callable(fn)

def test_profile_is_callable():
    """Function profile exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    fn = getattr(mod, "profile", None)
    assert fn is not None, "'profile' not found in transmogrifier.cli"
    assert callable(fn)

def test_profile_list_is_callable():
    """Function profile_list exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    fn = getattr(mod, "profile_list", None)
    assert fn is not None, "'profile_list' not found in transmogrifier.cli"
    assert callable(fn)

def test_profile_show_is_callable():
    """Function profile_show exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    fn = getattr(mod, "profile_show", None)
    assert fn is not None, "'profile_show' not found in transmogrifier.cli"
    assert callable(fn)

def test_profile_calibrate_is_callable():
    """Function profile_calibrate exists and is callable."""
    import importlib
    mod = importlib.import_module("transmogrifier.cli")
    fn = getattr(mod, "profile_calibrate", None)
    assert fn is not None, "'profile_calibrate' not found in transmogrifier.cli"
    assert callable(fn)
