"""Smoke tests for contracts/contracts_src_transmogrifier_rules_interface/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_contracts_src_transmogrifier_rules_interface_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_transmogrifier_rules_interface.interface")
    assert mod is not None

def test_rewrite_is_callable():
    """Function rewrite exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_transmogrifier_rules_interface.interface")
    fn = getattr(mod, "rewrite", None)
    assert fn is not None, "'rewrite' not found in contracts.contracts_src_transmogrifier_rules_interface.interface"
    assert callable(fn)
