"""Smoke tests for contracts/src_transmogrifier_mcp_server/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_src_transmogrifier_mcp_server_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_mcp_server.interface")
    assert mod is not None

def test_main_is_callable():
    """Function main exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_mcp_server.interface")
    fn = getattr(mod, "main", None)
    assert fn is not None, "'main' not found in contracts.src_transmogrifier_mcp_server.interface"
    assert callable(fn)

def test_transmog_translate_is_callable():
    """Function transmog_translate exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_mcp_server.interface")
    fn = getattr(mod, "transmog_translate", None)
    assert fn is not None, "'transmog_translate' not found in contracts.src_transmogrifier_mcp_server.interface"
    assert callable(fn)

def test_transmog_detect_is_callable():
    """Function transmog_detect exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_mcp_server.interface")
    fn = getattr(mod, "transmog_detect", None)
    assert fn is not None, "'transmog_detect' not found in contracts.src_transmogrifier_mcp_server.interface"
    assert callable(fn)

def test_transmog_profiles_is_callable():
    """Function transmog_profiles exists and is callable."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_mcp_server.interface")
    fn = getattr(mod, "transmog_profiles", None)
    assert fn is not None, "'transmog_profiles' not found in contracts.src_transmogrifier_mcp_server.interface"
    assert callable(fn)
