"""Smoke tests for contracts/src_transmogrifier_detector/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_src_transmogrifier_detector_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.src_transmogrifier_detector.interface")
    assert mod is not None
