"""Smoke tests for contracts/contracts_src_transmogrifier_task_classifier_interface/interface.py (auto-generated by pact adopt)."""

import pytest

def test_import_contracts_contracts_src_transmogrifier_task_classifier_interface_interface():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("contracts.contracts_src_transmogrifier_task_classifier_interface.interface")
    assert mod is not None
