"""Smoke tests for src/transmogrifier/backends/anthropic.py (auto-generated by pact adopt)."""

import pytest

def test_import_transmogrifier_backends_anthropic():
    """Module imports without error."""
    import importlib
    mod = importlib.import_module("transmogrifier.backends.anthropic")
    assert mod is not None
